// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6995.PatriciaTheCamel.subsystems;

import org.usfirst.frc6995.PatriciaTheCamel.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.DigitalInput;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;


/**
 *
 */
public class Lifter extends Subsystem {

    private final WPI_TalonSRX lifterMotorA = RobotMap.lifterLifterMotorA;
    private final WPI_TalonSRX lifterMotorB = RobotMap.lifterLifterMotorB;
    private final DigitalInput lifterTopSwitch = RobotMap.lifterLifterTopSwitch;
    private final DigitalInput lifterBottomSwitch = RobotMap.lifterLifterBottomSwitch;
    private final WPI_TalonSRX lifterRotatorMotor = RobotMap.lifterLifterRotatorMotor;

    // Initialize your subsystem here
    public Lifter() {

        // Use these to get going:
        // setSetpoint() -  Sets where the PID controller should move the system
        //                  to
        // enable() - Enables the PID controller.
    }

    @Override
    public void initDefaultCommand() {
 
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
