// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6995.PatriciaTheCamel.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class LifterComGroup extends CommandGroup {

	public final String groupName;  // OK to be public since final
	
	public LifterComGroup(String groupName) {
		this.groupName = groupName;
	}
	
    public LifterComGroup() {

    	this("unknown");
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	System.out.println(groupName + "initialized");
    	super.initialize();
    }

    // Called repeatedly when this Command is scheduled to run
    //@Override
    //protected void execute() {
    //}

    // Make this return true when this Command no longer needs to run execute()
    //@Override
    //protected boolean isFinished() {
    //    return false;
    //}

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	System.out.println(groupName + " ended");
    	super.end();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	System.out.println(groupName + " interrupted");
    	super.interrupted();
    }
}
